export const INCREMENT="INCREMENT"
export const DECREMENT="DECREMENT"

export const CREATE_USER_REQUEST ="CREATE_USER_REQUEST "
export const CREATE_USER_SUCCESS ="CREATE_USER_SUCCESS "
export const CREATE_USER_ERROR ="CREATE_USER_ERROR "

export const FERTCH_USER_REQUEST ="FERTCH_USER_REQUEST "
export const FERTCH_USER_SUCCESS ="FERTCH_USER_SUCCESS "
export const FERTCH_USER_ERROR ="FERTCH_USER_ERROR "