
export const CREATE_USER_REQUEST ="CREATE_USER_REQUEST "
export const CREATE_USER_SUCCESS ="CREATE_USER_SUCCESS "
export const CREATE_USER_ERROR ="CREATE_USER_ERROR "

export const FERTCH_USER_REQUEST ="FERTCH_USER_REQUEST "
export const FERTCH_USER_SUCCESS ="FERTCH_USER_SUCCESS "
export const FERTCH_USER_ERROR ="FERTCH_USER_ERROR "

export const GET_ALL_PAGINATE_REQUEST = "GET_ALL_PAGINATE_REQUEST"
export const GET_ALL_PAGINATE_SUCCESS = "GET_ALL_PAGINATE_SUCCESS"
export const GET_ALL_PAGINATE_ERROR = "GET_ALL_PAGINATE_ERROR"

export const FERTH_DEPARTMENT_REQUEST ='FERTH_DEPARTMENT_REQUEST'
export const FERTH_DEPARTMENT_SUCCESS ='FERTH_DEPARTMENT_SUCCESS'
export const FERTH_DEPARTMENT_ERROR ='FERTH_DEPARTMENT_ERROR'

export const GET_ALL_DOCTOR_REQUEST = "GET_ALL_DOCTOR_REQUEST"
export const GET_ALL_DOCTOR_SUCCESS = "GET_ALL_DOCTOR_SUCCESS"
export const GET_ALL_DOCTOR_ERROR = "GET_ALL_DOCTOR_ERROR"